//login/logout actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const LOADING_EMPLOYEES = "LOADING_EMPLOYEES";
export const EMPLOYEES_LOADED = "EMPLOYEES_LOADED";
export const DELETING_EMPLOYEE = "DELETING_EMPLOYEE";
export const EMPLOYEE_DELETED = "EMPLOYEE_DELETED";